### ISSUE TITLE
Text extracted in the wrong order

### ISSUE THREAD

**Issue by zafarali** [SamDecrock/pdf2table#2]
Hi, I have a table that looks like this:
![image](https://cloud.githubusercontent.com/assets/6295292/21168175/033f4f12-c180-11e6-9161-ed424f65ee20.png)

When I run the software I get the following output (for the actual table bit):
```
[ 'Intermediate Financial Acct 1',
  'GYM',
  'Dec 14',
  '2 pm',
  'Studio 1',
  'Tsang',
  'AAA',
  'LEE',
  '-',
  'ACCT 351',
  '001',
  '1-7' ]
```

Which is not the order in which the data is displayed?

I am doing some investigation into fixing this but would like to know if this was desired behaviour?

**Comment by SamDecrock** [comment]
The pdf is first parsed to json using pdf2json which outputs textfields with an x and y value. textfields are then grouped according to y value which I define as a "row".

My library doesn't order the found textfields by their x value. So the order is the order that comes out pdf2json.

You'll have to rewrite the library a bit, storing the text, x and y-value in the row-array and then order the elements of the row array by their x-value.
